### ISSUE TITLE
Latest ccreeninfo is not python3.6 compatible

### ISSUE THREAD

**Issue by dilawar** [BhallaLab/MouseBehaviour#60]
[100%] Built target cam_server
+ cd ..
+ python3 gui.py --build-dir /root/MouseBehaviour/_docker_build
Traceback (most recent call last):
  File "gui.py", line 25, in <module>
    from screeninfo import get_monitors
  File "/usr/local/lib/python3.6/dist-packages/screeninfo/__init__.py", line 1, in <module>
    from .common import Enumerator, Monitor
  File "/usr/local/lib/python3.6/dist-packages/screeninfo/common.py", line 3, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'
Makefile:14: recipe for target 'run' failed
make: *** [run] Error 1

New error after yesterday's  update

_Originally posted by @hrishi16 in https://github.com/BhallaLab/MouseBehaviour/issues/57#issuecomment-519191354_

**Comment by dilawar** [comment]
Related to #57 failure. Fixed by 6778a22 .
